/**
 * MOCK DATA UTILITY
 * 
 * This module contains all static mock datasets for the TBO Travel Copilot.
 * In a production environment, these would be replaced with real API calls.
 * 
 * Datasets include:
 * - Destinations
 * - Hotels
 * - Flights
 * - Activities
 * - Safety information
 */

// ============================================
// DESTINATIONS DATABASE
// ============================================

export const destinations = [
  {
    id: 'dubai-uae',
    name: 'Dubai',
    city: 'Dubai',
    country: 'UAE',
    continent: 'Asia',
    description: 'A luxury destination with modern architecture, shopping, and entertainment',
    popularMonths: ['Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    avgTemperature: { min: 20, max: 35 },
    currency: 'AED',
    timezone: 'UTC+4',
    bestFor: ['luxury', 'shopping', 'family', 'architecture'],
    safetyScore: 8.5,
    budgetRange: { min: 40000, max: 200000 },
    topAttractions: ['Burj Khalifa', 'Dubai Mall', 'Palm Jumeirah', 'Dubai Marina'],
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
  },
  {
    id: 'goa-india',
    name: 'Goa',
    city: 'Goa',
    country: 'India',
    continent: 'Asia',
    description: 'Beach paradise with Portuguese heritage, nightlife, and water sports',
    popularMonths: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb'],
    avgTemperature: { min: 22, max: 33 },
    currency: 'INR',
    timezone: 'UTC+5:30',
    bestFor: ['beach', 'party', 'relaxation', 'adventure'],
    safetyScore: 7.8,
    budgetRange: { min: 15000, max: 80000 },
    topAttractions: ['Baga Beach', 'Basilica of Bom Jesus', 'Dudhsagar Falls', 'Fort Aguada'],
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2',
  },
  {
    id: 'paris-france',
    name: 'Paris',
    city: 'Paris',
    country: 'France',
    continent: 'Europe',
    description: 'The city of love, art, fashion, and culinary excellence',
    popularMonths: ['Apr', 'May', 'Jun', 'Sep', 'Oct'],
    avgTemperature: { min: 5, max: 25 },
    currency: 'EUR',
    timezone: 'UTC+1',
    bestFor: ['romance', 'culture', 'art', 'food'],
    safetyScore: 7.5,
    budgetRange: { min: 100000, max: 300000 },
    topAttractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Champs-Élysées'],
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34',
  },
  {
    id: 'maldives',
    name: 'Maldives',
    city: 'Malé',
    country: 'Maldives',
    continent: 'Asia',
    description: 'Tropical paradise with crystal-clear waters and luxury resorts',
    popularMonths: ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
    avgTemperature: { min: 26, max: 31 },
    currency: 'MVR',
    timezone: 'UTC+5',
    bestFor: ['honeymoon', 'luxury', 'beach', 'diving'],
    safetyScore: 9.0,
    budgetRange: { min: 80000, max: 500000 },
    topAttractions: ['Underwater Restaurant', 'Bioluminescent Beach', 'Male City', 'Island Hopping'],
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8',
  },
  {
    id: 'bangkok-thailand',
    name: 'Bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    continent: 'Asia',
    description: 'Vibrant city with temples, street food, nightlife, and shopping',
    popularMonths: ['Nov', 'Dec', 'Jan', 'Feb'],
    avgTemperature: { min: 25, max: 35 },
    currency: 'THB',
    timezone: 'UTC+7',
    bestFor: ['culture', 'food', 'shopping', 'nightlife'],
    safetyScore: 7.9,
    budgetRange: { min: 30000, max: 120000 },
    topAttractions: ['Grand Palace', 'Wat Pho', 'Chatuchak Market', 'Floating Markets'],
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365',
  },
  {
    id: 'manali-india',
    name: 'Manali',
    city: 'Manali',
    country: 'India',
    continent: 'Asia',
    description: 'Hill station with snow-capped mountains, adventure sports, and scenic beauty',
    popularMonths: ['Apr', 'May', 'Jun', 'Dec', 'Jan'],
    avgTemperature: { min: -1, max: 25 },
    currency: 'INR',
    timezone: 'UTC+5:30',
    bestFor: ['adventure', 'nature', 'honeymoon', 'trekking'],
    safetyScore: 8.2,
    budgetRange: { min: 12000, max: 60000 },
    topAttractions: ['Rohtang Pass', 'Solang Valley', 'Hidimba Temple', 'Old Manali'],
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    city: 'Singapore',
    country: 'Singapore',
    continent: 'Asia',
    description: 'Modern city-state with futuristic architecture, gardens, and diverse cuisine',
    popularMonths: ['Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
    avgTemperature: { min: 25, max: 32 },
    currency: 'SGD',
    timezone: 'UTC+8',
    bestFor: ['family', 'food', 'urban', 'shopping'],
    safetyScore: 9.5,
    budgetRange: { min: 50000, max: 180000 },
    topAttractions: ['Marina Bay Sands', 'Gardens by the Bay', 'Universal Studios', 'Sentosa Island'],
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd',
  },
  {
    id: 'jaipur-india',
    name: 'Jaipur',
    city: 'Jaipur',
    country: 'India',
    continent: 'Asia',
    description: 'The Pink City with royal palaces, forts, and vibrant culture',
    popularMonths: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
    avgTemperature: { min: 10, max: 40 },
    currency: 'INR',
    timezone: 'UTC+5:30',
    bestFor: ['culture', 'history', 'photography', 'shopping'],
    safetyScore: 7.5,
    budgetRange: { min: 8000, max: 50000 },
    topAttractions: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar'],
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41',
  },
];

// ============================================
// HOTELS DATABASE
// ============================================

export const hotels = [
  // Dubai Hotels
  {
    id: 'hotel-dubai-1',
    name: 'Burj Al Arab Jumeirah',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    rating: 5,
    category: 'luxury',
    price: 45000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Jumeirah Beach',
    distanceFromCenter: 5,
    amenities: ['Pool', 'Spa', 'Restaurant', 'Beach Access', 'Butler Service', 'Helipad'],
    roomTypes: ['Deluxe Suite', 'Panoramic Suite', 'Royal Suite'],
    familyFriendly: true,
    reviewCount: 5200,
    reviewScore: 9.5,
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
    description: 'Iconic 7-star luxury hotel with stunning architecture',
    cancellationPolicy: 'Free cancellation up to 7 days before check-in',
  },
  {
    id: 'hotel-dubai-2',
    name: 'Atlantis The Palm',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    rating: 5,
    category: 'luxury',
    price: 28000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Palm Jumeirah',
    distanceFromCenter: 7,
    amenities: ['Water Park', 'Aquarium', 'Pool', 'Spa', 'Multiple Restaurants', 'Kids Club'],
    roomTypes: ['Imperial Club', 'Deluxe Room', 'Underwater Suite'],
    familyFriendly: true,
    reviewCount: 8900,
    reviewScore: 9.2,
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb'],
    description: 'Resort with aquarium, water park, and beach access',
    cancellationPolicy: 'Free cancellation up to 5 days before check-in',
  },
  {
    id: 'hotel-dubai-3',
    name: 'Jumeirah Beach Hotel',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    rating: 4,
    category: 'mid-range',
    price: 18000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Jumeirah Beach',
    distanceFromCenter: 6,
    amenities: ['Pool', 'Beach', 'Gym', 'Restaurant', 'Free WiFi'],
    roomTypes: ['Deluxe Room', 'Ocean View', 'Family Suite'],
    familyFriendly: true,
    reviewCount: 4200,
    reviewScore: 8.8,
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'],
    description: 'Family-friendly beach hotel with modern amenities',
    cancellationPolicy: 'Free cancellation up to 3 days before check-in',
  },
  {
    id: 'hotel-dubai-4',
    name: 'Rove Downtown Dubai',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    rating: 3,
    category: 'budget',
    price: 8000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Downtown Dubai',
    distanceFromCenter: 2,
    amenities: ['Pool', 'Gym', 'Free WiFi', 'Breakfast'],
    roomTypes: ['Standard Room', 'Twin Room'],
    familyFriendly: true,
    reviewCount: 3100,
    reviewScore: 8.3,
    images: ['https://images.unsplash.com/photo-1611892440504-42a792e24d32'],
    description: 'Budget-friendly hotel near Dubai Mall and Burj Khalifa',
    cancellationPolicy: 'Free cancellation up to 1 day before check-in',
  },

  // Goa Hotels
  {
    id: 'hotel-goa-1',
    name: 'Taj Exotica Resort & Spa',
    destination: 'Goa',
    destinationId: 'goa-india',
    rating: 5,
    category: 'luxury',
    price: 22000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Benaulim Beach',
    distanceFromCenter: 8,
    amenities: ['Private Beach', 'Spa', 'Pool', 'Multiple Restaurants', 'Water Sports'],
    roomTypes: ['Deluxe Room', 'Premium Villa', 'Presidential Suite'],
    familyFriendly: true,
    reviewCount: 2800,
    reviewScore: 9.1,
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9'],
    description: 'Luxury beach resort with Portuguese-inspired architecture',
    cancellationPolicy: 'Free cancellation up to 5 days before check-in',
  },
  {
    id: 'hotel-goa-2',
    name: 'The Leela Goa',
    destination: 'Goa',
    destinationId: 'goa-india',
    rating: 5,
    category: 'luxury',
    price: 18000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Mobor Beach',
    distanceFromCenter: 12,
    amenities: ['Beach', 'Lagoon', 'Golf Course', 'Spa', 'Casino', 'Pool'],
    roomTypes: ['Premium Room', 'Beach Villa', 'Club Room'],
    familyFriendly: true,
    reviewCount: 3400,
    reviewScore: 8.9,
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791'],
    description: 'Sprawling resort with lagoons and pristine beach',
    cancellationPolicy: 'Free cancellation up to 7 days before check-in',
  },
  {
    id: 'hotel-goa-3',
    name: 'Alila Diwa Goa',
    destination: 'Goa',
    destinationId: 'goa-india',
    rating: 4,
    category: 'mid-range',
    price: 12000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Majorda Beach',
    distanceFromCenter: 10,
    amenities: ['Pool', 'Spa', 'Restaurant', 'Beach Access', 'Gym'],
    roomTypes: ['Deluxe Room', 'Terrace Room', 'Suite'],
    familyFriendly: true,
    reviewCount: 1900,
    reviewScore: 8.7,
    images: ['https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f'],
    description: 'Contemporary resort blending Goan tradition with modern luxury',
    cancellationPolicy: 'Free cancellation up to 3 days before check-in',
  },
  {
    id: 'hotel-goa-4',
    name: 'Treebo Trend O Goa',
    destination: 'Goa',
    destinationId: 'goa-india',
    rating: 3,
    category: 'budget',
    price: 3500,
    currency: 'INR',
    pricePerNight: true,
    location: 'Candolim',
    distanceFromCenter: 5,
    amenities: ['Free WiFi', 'Breakfast', 'AC', 'Room Service'],
    roomTypes: ['Standard Room', 'Deluxe Room'],
    familyFriendly: false,
    reviewCount: 850,
    reviewScore: 7.8,
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427'],
    description: 'Budget hotel near Candolim Beach',
    cancellationPolicy: 'Free cancellation up to 1 day before check-in',
  },

  // Singapore Hotels
  {
    id: 'hotel-singapore-1',
    name: 'Marina Bay Sands',
    destination: 'Singapore',
    destinationId: 'singapore',
    rating: 5,
    category: 'luxury',
    price: 32000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Marina Bay',
    distanceFromCenter: 1,
    amenities: ['Infinity Pool', 'Casino', 'Shopping Mall', 'Spa', 'Multiple Restaurants', 'Rooftop Bar'],
    roomTypes: ['Deluxe Room', 'Premier Room', 'Club Room'],
    familyFriendly: true,
    reviewCount: 12000,
    reviewScore: 9.3,
    images: ['https://images.unsplash.com/photo-1585146777747-f87364a74f6b'],
    description: 'Iconic hotel with world-famous rooftop infinity pool',
    cancellationPolicy: 'Free cancellation up to 3 days before check-in',
  },
  {
    id: 'hotel-singapore-2',
    name: 'Raffles Hotel Singapore',
    destination: 'Singapore',
    destinationId: 'singapore',
    rating: 5,
    category: 'luxury',
    price: 38000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Colonial District',
    distanceFromCenter: 1.5,
    amenities: ['Pool', 'Spa', 'Fine Dining', 'Butler Service', 'Museum'],
    roomTypes: ['Courtyard Suite', 'Palm Court Suite', 'Presidential Suite'],
    familyFriendly: false,
    reviewCount: 3800,
    reviewScore: 9.6,
    images: ['https://images.unsplash.com/photo-1584132967334-10e028bd69f7'],
    description: 'Historic luxury hotel with colonial charm',
    cancellationPolicy: 'Free cancellation up to 7 days before check-in',
  },
  {
    id: 'hotel-singapore-3',
    name: 'Park Royal on Pickering',
    destination: 'Singapore',
    destinationId: 'singapore',
    rating: 4,
    category: 'mid-range',
    price: 15000,
    currency: 'INR',
    pricePerNight: true,
    location: 'Chinatown',
    distanceFromCenter: 1,
    amenities: ['Sky Gardens', 'Pool', 'Gym', 'Restaurant', 'Free WiFi'],
    roomTypes: ['Deluxe Room', 'Studio', 'Suite'],
    familyFriendly: true,
    reviewCount: 2600,
    reviewScore: 8.8,
    images: ['https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0'],
    description: 'Award-winning eco-friendly hotel with sky gardens',
    cancellationPolicy: 'Free cancellation up to 2 days before check-in',
  },
];

// ============================================
// FLIGHTS DATABASE
// ============================================

export const flights = [
  // India to Dubai
  {
    id: 'flight-1',
    flightNumber: 'AI995',
    airline: 'Air India',
    from: 'Delhi (DEL)',
    fromCity: 'Delhi',
    fromCountry: 'India',
    to: 'Dubai (DXB)',
    toCity: 'Dubai',
    toCountry: 'UAE',
    departure: '06:00',
    arrival: '08:30',
    duration: '3h 30m',
    stops: 0,
    class: 'Economy',
    price: 18000,
    currency: 'INR',
    availableSeats: 42,
    baggage: '30kg',
    cancellationFee: 3000,
    refundable: true,
  },
  {
    id: 'flight-2',
    flightNumber: 'EK512',
    airline: 'Emirates',
    from: 'Mumbai (BOM)',
    fromCity: 'Mumbai',
    fromCountry: 'India',
    to: 'Dubai (DXB)',
    toCity: 'Dubai',
    toCountry: 'UAE',
    departure: '10:30',
    arrival: '12:45',
    duration: '3h 15m',
    stops: 0,
    class: 'Economy',
    price: 22000,
    currency: 'INR',
    availableSeats: 28,
    baggage: '30kg',
    cancellationFee: 3500,
    refundable: true,
  },
  {
    id: 'flight-3',
    flightNumber: 'EK502',
    airline: 'Emirates',
    from: 'Mumbai (BOM)',
    fromCity: 'Mumbai',
    fromCountry: 'India',
    to: 'Dubai (DXB)',
    toCity: 'Dubai',
    toCountry: 'UAE',
    departure: '03:45',
    arrival: '06:00',
    duration: '3h 15m',
    stops: 0,
    class: 'Business',
    price: 65000,
    currency: 'INR',
    availableSeats: 8,
    baggage: '40kg',
    cancellationFee: 8000,
    refundable: true,
  },
  // India to Singapore
  {
    id: 'flight-4',
    flightNumber: 'SQ402',
    airline: 'Singapore Airlines',
    from: 'Delhi (DEL)',
    fromCity: 'Delhi',
    fromCountry: 'India',
    to: 'Singapore (SIN)',
    toCity: 'Singapore',
    toCountry: 'Singapore',
    departure: '22:00',
    arrival: '05:30',
    duration: '6h 30m',
    stops: 0,
    class: 'Economy',
    price: 28000,
    currency: 'INR',
    availableSeats: 35,
    baggage: '30kg',
    cancellationFee: 4000,
    refundable: true,
  },
  {
    id: 'flight-5',
    flightNumber: 'AI382',
    airline: 'Air India',
    from: 'Mumbai (BOM)',
    fromCity: 'Mumbai',
    fromCountry: 'India',
    to: 'Singapore (SIN)',
    toCity: 'Singapore',
    toCountry: 'Singapore',
    departure: '09:15',
    arrival: '17:00',
    duration: '5h 45m',
    stops: 0,
    class: 'Economy',
    price: 25000,
    currency: 'INR',
    availableSeats: 52,
    baggage: '30kg',
    cancellationFee: 3500,
    refundable: true,
  },
  // Domestic India
  {
    id: 'flight-6',
    flightNumber: '6E2135',
    airline: 'IndiGo',
    from: 'Delhi (DEL)',
    fromCity: 'Delhi',
    fromCountry: 'India',
    to: 'Goa (GOI)',
    toCity: 'Goa',
    toCountry: 'India',
    departure: '07:00',
    arrival: '09:30',
    duration: '2h 30m',
    stops: 0,
    class: 'Economy',
    price: 4500,
    currency: 'INR',
    availableSeats: 68,
    baggage: '15kg',
    cancellationFee: 1500,
    refundable: false,
  },
  {
    id: 'flight-7',
    flightNumber: 'SG8194',
    airline: 'SpiceJet',
    from: 'Mumbai (BOM)',
    fromCity: 'Mumbai',
    fromCountry: 'India',
    to: 'Goa (GOI)',
    toCity: 'Goa',
    toCountry: 'India',
    departure: '15:30',
    arrival: '17:00',
    duration: '1h 30m',
    stops: 0,
    class: 'Economy',
    price: 3200,
    currency: 'INR',
    availableSeats: 45,
    baggage: '15kg',
    cancellationFee: 1200,
    refundable: false,
  },
  {
    id: 'flight-8',
    flightNumber: 'UK829',
    airline: 'Vistara',
    from: 'Delhi (DEL)',
    fromCity: 'Delhi',
    fromCountry: 'India',
    to: 'Jaipur (JAI)',
    toCity: 'Jaipur',
    toCountry: 'India',
    departure: '06:30',
    arrival: '07:45',
    duration: '1h 15m',
    stops: 0,
    class: 'Economy',
    price: 3800,
    currency: 'INR',
    availableSeats: 72,
    baggage: '15kg',
    cancellationFee: 1000,
    refundable: false,
  },
];

// ============================================
// ACTIVITIES DATABASE
// ============================================

export const activities = [
  // Dubai Activities
  {
    id: 'activity-dubai-1',
    name: 'Burj Khalifa At The Top',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    category: 'sightseeing',
    price: 3500,
    currency: 'INR',
    duration: '2h',
    description: 'Visit the world\'s tallest building with stunning city views',
    location: 'Downtown Dubai',
    rating: 9.2,
    reviewCount: 45000,
    bestTimeToVisit: 'Sunset',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1512632578888-169bbbc64f33'],
  },
  {
    id: 'activity-dubai-2',
    name: 'Desert Safari with BBQ Dinner',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    category: 'adventure',
    price: 4200,
    currency: 'INR',
    duration: '6h',
    description: 'Dune bashing, camel ride, sandboarding, and traditional BBQ dinner',
    location: 'Dubai Desert',
    rating: 9.0,
    reviewCount: 32000,
    bestTimeToVisit: 'Evening',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3'],
  },
  {
    id: 'activity-dubai-3',
    name: 'Dubai Marina Yacht Cruise',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    category: 'relaxation',
    price: 5500,
    currency: 'INR',
    duration: '2h',
    description: 'Luxury yacht cruise with dinner and views of Dubai skyline',
    location: 'Dubai Marina',
    rating: 8.8,
    reviewCount: 12000,
    bestTimeToVisit: 'Evening',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1567899378494-47b22a2ae96a'],
  },
  {
    id: 'activity-dubai-4',
    name: 'Dubai Mall & Aquarium',
    destination: 'Dubai',
    destinationId: 'dubai-uae',
    category: 'shopping',
    price: 1500,
    currency: 'INR',
    duration: '4h',
    description: 'World\'s largest shopping mall with aquarium and underwater zoo',
    location: 'Downtown Dubai',
    rating: 8.9,
    reviewCount: 28000,
    bestTimeToVisit: 'Anytime',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8'],
  },

  // Goa Activities
  {
    id: 'activity-goa-1',
    name: 'Water Sports Package',
    destination: 'Goa',
    destinationId: 'goa-india',
    category: 'adventure',
    price: 2500,
    currency: 'INR',
    duration: '3h',
    description: 'Parasailing, jet ski, banana boat, and bumper ride',
    location: 'Baga Beach',
    rating: 8.7,
    reviewCount: 8500,
    bestTimeToVisit: 'Morning',
    familyFriendly: false,
    images: ['https://images.unsplash.com/photo-1559827260-dc66d52bef19'],
  },
  {
    id: 'activity-goa-2',
    name: 'Dudhsagar Falls & Spice Plantation',
    destination: 'Goa',
    destinationId: 'goa-india',
    category: 'sightseeing',
    price: 1800,
    currency: 'INR',
    duration: '7h',
    description: 'Jeep safari to waterfall, spice plantation tour, and lunch',
    location: 'South Goa',
    rating: 9.1,
    reviewCount: 12000,
    bestTimeToVisit: 'Morning',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5'],
  },
  {
    id: 'activity-goa-3',
    name: 'Sunset Cruise with Music',
    destination: 'Goa',
    destinationId: 'goa-india',
    category: 'relaxation',
    price: 1200,
    currency: 'INR',
    duration: '2h',
    description: 'River cruise with live music, DJ, and unlimited drinks',
    location: 'Mandovi River',
    rating: 8.5,
    reviewCount: 6700,
    bestTimeToVisit: 'Evening',
    familyFriendly: false,
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5'],
  },
  {
    id: 'activity-goa-4',
    name: 'Old Goa Heritage Walk',
    destination: 'Goa',
    destinationId: 'goa-india',
    category: 'cultural',
    price: 800,
    currency: 'INR',
    duration: '3h',
    description: 'Guided tour of Portuguese churches and UNESCO sites',
    location: 'Old Goa',
    rating: 8.3,
    reviewCount: 3400,
    bestTimeToVisit: 'Morning',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2'],
  },

  // Singapore Activities
  {
    id: 'activity-singapore-1',
    name: 'Universal Studios Singapore',
    destination: 'Singapore',
    destinationId: 'singapore',
    category: 'adventure',
    price: 5200,
    currency: 'INR',
    duration: '8h',
    description: 'Southeast Asia\'s first and only Universal Studios theme park',
    location: 'Sentosa Island',
    rating: 9.3,
    reviewCount: 38000,
    bestTimeToVisit: 'Morning',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96'],
  },
  {
    id: 'activity-singapore-2',
    name: 'Gardens by the Bay & Supertree',
    destination: 'Singapore',
    destinationId: 'singapore',
    category: 'sightseeing',
    price: 2200,
    currency: 'INR',
    duration: '3h',
    description: 'Cloud Forest, Flower Dome, and Supertree light show',
    location: 'Marina Bay',
    rating: 9.5,
    reviewCount: 52000,
    bestTimeToVisit: 'Evening',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1525625293386-3f8f99389edd'],
  },
  {
    id: 'activity-singapore-3',
    name: 'Night Safari',
    destination: 'Singapore',
    destinationId: 'singapore',
    category: 'adventure',
    price: 3200,
    currency: 'INR',
    duration: '4h',
    description: 'World\'s first nocturnal wildlife park with tram ride',
    location: 'Mandai',
    rating: 9.0,
    reviewCount: 24000,
    bestTimeToVisit: 'Evening',
    familyFriendly: true,
    images: ['https://images.unsplash.com/photo-1564760055775-d63b17a55c44'],
  },
];

// ============================================
// SAFETY INFORMATION
// ============================================

export const safetyData = {
  'Dubai': {
    overallScore: 8.5,
    categories: {
      crime: 9.2,
      health: 8.8,
      naturalDisasters: 7.5,
      terrorism: 7.8,
      womenSafety: 8.9,
      soloTraveler: 8.7,
    },
    warnings: [
      {
        type: 'cultural',
        severity: 'medium',
        message: 'Dress modestly in public places outside resorts',
      },
      {
        type: 'weather',
        severity: 'low',
        message: 'Extreme heat during summer (June-August), stay hydrated',
      },
    ],
    emergencyContacts: {
      police: '999',
      ambulance: '998',
      touristPolice: '901',
    },
    tips: [
      'Avoid public displays of affection',
      'Always carry ID/passport copy',
      'Taxis are safe and metered',
      'Friday is a holy day, some places closed',
    ],
  },
  'Goa': {
    overallScore: 7.8,
    categories: {
      crime: 7.5,
      health: 7.2,
      naturalDisasters: 8.5,
      terrorism: 8.0,
      womenSafety: 7.3,
      soloTraveler: 7.8,
    },
    warnings: [
      {
        type: 'safety',
        severity: 'medium',
        message: 'Be cautious at late-night beach parties',
      },
      {
        type: 'health',
        severity: 'low',
        message: 'Drink bottled water, be careful with street food',
      },
      {
        type: 'women-safety',
        severity: 'medium',
        message: 'Women travelers should avoid isolated beaches after dark',
      },
    ],
    emergencyContacts: {
      police: '100',
      ambulance: '102',
      touristPolice: '1800-111-363',
    },
    tips: [
      'Bargain at local markets',
      'Rent scooters only if confident with Indian traffic',
      'Book accommodations in advance during peak season',
      'Be aware of monsoon season (June-September)',
    ],
  },
  'Singapore': {
    overallScore: 9.5,
    categories: {
      crime: 9.8,
      health: 9.7,
      naturalDisasters: 9.2,
      terrorism: 8.5,
      womenSafety: 9.9,
      soloTraveler: 9.7,
    },
    warnings: [
      {
        type: 'legal',
        severity: 'high',
        message: 'Strict laws: No chewing gum, no littering (heavy fines)',
      },
      {
        type: 'legal',
        severity: 'high',
        message: 'Drug trafficking carries death penalty',
      },
    ],
    emergencyContacts: {
      police: '999',
      ambulance: '995',
      touristHelpline: '1800-736-2000',
    },
    tips: [
      'One of the safest cities in the world',
      'Public transport is excellent and safe',
      'Follow all rules strictly to avoid fines',
      'English is widely spoken',
    ],
  },
  'Paris': {
    overallScore: 7.5,
    categories: {
      crime: 6.8,
      health: 8.5,
      naturalDisasters: 8.8,
      terrorism: 6.5,
      womenSafety: 7.2,
      soloTraveler: 7.8,
    },
    warnings: [
      {
        type: 'crime',
        severity: 'high',
        message: 'Pickpocketing is common at tourist sites and metro',
      },
      {
        type: 'safety',
        severity: 'medium',
        message: 'Avoid certain suburbs late at night',
      },
    ],
    emergencyContacts: {
      police: '17',
      ambulance: '15',
      touristPolice: '+33 1 53 71 53 71',
    },
    tips: [
      'Keep valuables secure at all times',
      'Be cautious around Eiffel Tower and Sacré-Cœur',
      'Learn basic French phrases',
      'Metro is efficient but crowded during rush hour',
    ],
  },
  'Maldives': {
    overallScore: 9.0,
    categories: {
      crime: 9.3,
      health: 8.5,
      naturalDisasters: 7.8,
      terrorism: 9.0,
      womenSafety: 9.2,
      soloTraveler: 8.9,
    },
    warnings: [
      {
        type: 'natural',
        severity: 'low',
        message: 'Low-lying islands, climate change concerns',
      },
      {
        type: 'cultural',
        severity: 'medium',
        message: 'Conservative Muslim country outside resorts',
      },
    ],
    emergencyContacts: {
      police: '119',
      ambulance: '102',
      coastGuard: '191',
    },
    tips: [
      'Resorts are very safe and secluded',
      'Dress modestly if visiting local islands',
      'No alcohol on local islands (only in resorts)',
      'Check resort transfer costs in advance',
    ],
  },
  'Bangkok': {
    overallScore: 7.9,
    categories: {
      crime: 7.6,
      health: 7.4,
      naturalDisasters: 8.0,
      terrorism: 8.2,
      womenSafety: 7.8,
      soloTraveler: 8.3,
    },
    warnings: [
      {
        type: 'scam',
        severity: 'medium',
        message: 'Common tourist scams: tuk-tuk overcharging, gem scams',
      },
      {
        type: 'health',
        severity: 'low',
        message: 'Drink bottled water, be cautious with street food',
      },
    ],
    emergencyContacts: {
      police: '191',
      ambulance: '1669',
      touristPolice: '1155',
    },
    tips: [
      'Use metered taxis or Grab app',
      'Dress modestly when visiting temples',
      'Negotiate tuk-tuk prices before riding',
      'Stay hydrated in the heat',
    ],
  },
  'Manali': {
    overallScore: 8.2,
    categories: {
      crime: 8.5,
      health: 7.8,
      naturalDisasters: 7.0,
      terrorism: 8.8,
      womenSafety: 7.9,
      soloTraveler: 8.4,
    },
    warnings: [
      {
        type: 'natural',
        severity: 'high',
        message: 'Road closures during heavy snow, landslides in monsoon',
      },
      {
        type: 'health',
        severity: 'medium',
        message: 'Altitude sickness possible, acclimatize properly',
      },
    ],
    emergencyContacts: {
      police: '100',
      ambulance: '102',
      disaster: '1070',
    },
    tips: [
      'Check road conditions before traveling',
      'Carry warm clothes even in summer',
      'Book hotels in advance during peak season',
      'Adventure activities are generally safe but use licensed operators',
    ],
  },
  'Jaipur': {
    overallScore: 7.5,
    categories: {
      crime: 7.3,
      health: 7.0,
      naturalDisasters: 8.5,
      terrorism: 7.8,
      womenSafety: 7.0,
      soloTraveler: 7.7,
    },
    warnings: [
      {
        type: 'health',
        severity: 'medium',
        message: 'Extreme heat in summer (April-June), drink water',
      },
      {
        type: 'scam',
        severity: 'medium',
        message: 'Be cautious of gem/carpet scams and overcharging',
      },
    ],
    emergencyContacts: {
      police: '100',
      ambulance: '102',
      touristPolice: '0141-2200175',
    },
    tips: [
      'Hire government-approved guides at monuments',
      'Use prepaid taxis or Uber/Ola',
      'Bargain at bazaars',
      'Dress modestly when visiting religious sites',
    ],
  },
};
